# Generated by Django 3.2.9 on 2022-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220524_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='machine_images/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
