# Generated by Django 3.2.9 on 2022-05-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
