# Generated by Django 3.2.9 on 2022-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220527_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='rent',
            new_name='for_rent',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='sell',
            new_name='for_sale',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='industry',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='warrenty',
            new_name='warranty',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='fetures',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='price',
        ),
        migrations.AddField(
            model_name='machine',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
