# Generated by Django 3.2.9 on 2022-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220528_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='details',
            field=models.JSONField(null=True),
        ),
    ]
