# Generated by Django 3.2.9 on 2022-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_machine_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
