# Generated by Django 3.2.9 on 2022-05-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_residue_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.residue')),
            ],
        ),
    ]
