# Generated by Django 3.2.9 on 2022-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_residueorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
