# Generated by Django 3.2.9 on 2022-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_machine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='type_of_residue',
            field=models.CharField(choices=[('Rice Straw', 'Rice Straw'), ('Wheat Straw', 'Wheat Straw'), ('Rice Husk', 'Rice Husk'), ('Corn Stover', 'Corn Stover'), ('Forestry Residues', 'Forestry Residues'), ('Others', 'Others')], default='Rice Straw', max_length=200),
        ),
    ]
