# Generated by Django 4.0.5 on 2022-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_residue_type_of_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='House Address', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='City', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='name_of_recipient',
            field=models.CharField(default='Reciever', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='State', max_length=30),
        ),
    ]
