# Generated by Django 4.0.5 on 2022-07-18 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_residue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueorder',
            name='address',
            field=models.CharField(default='House Address', max_length=300),
        ),
        migrations.AddField(
            model_name='residueorder',
            name='city',
            field=models.CharField(default='City', max_length=15),
        ),
        migrations.AddField(
            model_name='residueorder',
            name='name_of_recipient',
            field=models.CharField(default='Reciever', max_length=30),
        ),
        migrations.AddField(
            model_name='residueorder',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='residueorder',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='residueorder',
            name='state',
            field=models.CharField(default='State', max_length=30),
        ),
    ]
